name: Back

on:
  push:
    branches: 
      - master
    paths: 
      - back/**
  pull_request:  # [master, next]
    paths: 
      - back/**

jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: back

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release -r win-x64 --output ./publish XdPagamentosApi.sln
      
    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.api.xdpayment.sis-pro.net
        username: api
        password: seit19790520
        protocol: ftp
        port: 21
